name: PoliNLP CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-pipeline-without-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH

      - name: Install dependencies (with the project package)
        run: poetry install --no-interaction  # Remove --no-root so the package is installed

      - name: Ensure `run.sh` is executable
        run: chmod +x run.sh

      - name: Run full pipeline (without tests)
        run: ./run.sh --skip-tests

  run-tests-separately:
    runs-on: ubuntu-latest
    needs: run-pipeline-without-tests  # Wait for the pipeline to finish

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH

      - name: Install dependencies (with the project package)
        run: poetry install --no-interaction  # Same modification here

      - name: Run tests separately
        run: poetry run pytest tests/ --tb=short
